[package]
name = "lumi_v2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lexical = "7.0.4"
num-traits = "0.2.19"
sysinfo = "0.33.1"

[features]
trace_exec = []
bench = []
